dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

 


compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
  


deployed:

  


networks:
    mainnet-fork:
        gas_limit: max
        gas_buffer: 1
        gas_price: 5
        reverting_tx_gas_limit: max
        default_contract_owner: true
    matic:
        gas_limit: max
        gas_buffer: 10
        gas_price: 50
        reverting_tx_gas_limit: max
        default_contract_owner: true

    